# app/config/routing.yml

gseb_validation:
    resource: "@GSEBValidationBundle/Resources/config/routing.yml"
    prefix:   /

gseb_historique:
    resource: "@GSEBHistoriqueBundle/Resources/config/routing.yml"
    prefix:   /

gseb_platform:
    resource: "@GSEBPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

gseb_core:
    resource: "@GSEBCoreBundle/Resources/config/routing.yml"

login:
    path: /login
    defaults:
        _controller: GSEBUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
