gseb_historique:
    resource: "@GSEBHistoriqueBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

gseb_platform:
    resource: "@GSEBPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

# On inclut également les routes de notre CoreBundle, sans préfixe
gseb_core:
    resource: "@GSEBCoreBundle/Resources/config/routing.yml"

# login:
#     path: /login
#     defaults:
#         _controller: SEBUserBundle:Security:login

# login_check:
#     path: /login_check

# logout:
#     path: /logout
