<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMlpfgke\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMlpfgke/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMlpfgke.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMlpfgke\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMlpfgke\appProdProjectContainer(array(
    'container.build_hash' => 'Mlpfgke',
    'container.build_id' => '293dee27',
    'container.build_time' => 1533806748,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMlpfgke');
