# src/SEB/CoreBundle/Resources/config/routing.yml

gseb_core_home:
    path: /
    defaults:
        _controller: GSEBCoreBundle:Core:index

# Intéressant pour éventuellement reporter des bugs
# oc_core_contact:
#     path: /contact
#     defaults:
#         _controller: OCCoreBundle:Core:contact
