<?php

namespace GSEB\PlatformBundle\Repository;

/**
 * AttributRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributRepository extends \Doctrine\ORM\EntityRepository
{
}
