<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyx1vrd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyx1vrd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXyx1vrd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXyx1vrd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXyx1vrd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xyx1vrd',
    'container.build_id' => 'ecee276b',
    'container.build_time' => 1534170230,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyx1vrd');
